# Numpy Tutorial

In [ ]:
#Import numpy
import numpy as np

## The Basics

In [ ]:
a = np.array([1,2,3]) # One dimensional array (int64 by default)
print ("a = ", a)
print (a.ndim) # Dimensions
print (a.shape) # Shape
print (a.dtype) # Memory type
print (a.itemsize) #bytes of each item
print (a.size) # Number of elements
print (a.nbytes) # Total memory

In [ ]:
b = np.array([[1.1,2.2,3.3],[4.4,5.5,6.6],[7.7,8.8,9.9]]) # Two dimensional float array (float64 by default)
print("b = ", b)
print (b.ndim) # Dimensions
print (b.shape) # Shape
print (b.dtype) # Memory type
print (b.itemsize) #bytes of each item
print (b.size) # Number of elements
print (b.nbytes) # Total memory

## Accessing/Changing specific elements, rows, columns, etc.

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

# Get a specific element [r,c] indexing from 0
print (a[1,2]) # row 1 column 2
print (a[0,:]) # first row
print (a[:,2]) # second column
print (a[0,1:-1:2]) #first to six 2by2, first row

# Changing values
a[0,0] = 99; print (a)
a[:,1] = [77,88]; print(a)

# 3D exemple
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print (b)
print (b[0,:,:]) # first index is "deepnes"
b[:,1,:] = [[8,8],[9,9]]; print (b)

## Initializing different type of arrays

In [ ]:
# Array of zeros
print (np.zeros(5))
print (np.zeros((3,2))) 

# Array of ones
print (np.ones(5))
print (np.ones((3,2))) 

# Other numbers
print (np.full(5,99))
print (np.full((3,2),99))

# From other array shapes
a = np.array([2,3])
print (np.full(a.shape,4))
print (np.full_like(a,4))

# Random decimal numbers 
print (np.random.rand(2,3)) # np.random.rand() returns decimal numbers between 0 and 1
print (np.random.random_sample(a.shape))

# Random int numbers
print (np.random.randint(5,10, size = a.size)) # random int from low (0 if None) to high of size ()

# Id matrix
print (np.identity(5))

# Copying arrays different id
b = a.copy() 
b[0] = 100
print (b, a) 

# Linear spaced vector
c, step = np.linspace(1, 10, 20, endpoint = False, retstep = True) #start, end, steps, end inclusive, return step size
print (step)
print (c) 

## Maths

In [ ]:
a = np.array([1,2,3]); print (a)
b = np.array([1,0,1]); print (b)

# Basic operations
print (a+2)
print (a-2)
print (a*2)
print (a/2)
print (a**2)
print (a+b)

## Linear Algebra

In [ ]:
a = np.ones((2,3)); print (a)
b = np.full((3,4), 2); print (b)

# Basic operations
print (np.matmul(a,b)) # Multiply
print (np.multiply(b,b)) # Logic wise multiplication
print (np.linalg.det(np.identity(3))) # Package np.linalg for more things


## Statistics

In [ ]:
a = np.array([[1,2,3],[4,5,6]])

# Basic operations
print (np.max(a)) #max
print (np.min(a, axis = 0)) #min
print (np.sum(a)) #sum

## Reorganizing Arrays

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,2,3])

# Reshape
print (a)
print (a.reshape((6,1)))
print (a.reshape((3,2)))

# Stack
print (np.vstack([b,b]))
print (np.hstack([b,b]))

## Load Data

In [ ]:
# Import data from a txt file as an array
data = np.genfromtxt("data.txt", delimiter = ",") # float by default
data = data.astype("int32") # transform to int
print (data)

## Boolean Indexing

In [149]:
# Data to work
data = np.genfromtxt("data.txt", delimiter = ",") # float by default
data = data.astype("int32") # transform to int
print (data)

# Bool array
print (data > 20) 
print (data[data < 20]) # indexing with bool return 1D
print (np.any(data > 400, axis = 0)) # any > 400 in each column
print (np.all(data < 200, axis = 0)) # all < 200 in each column
print (np.all(~(data < 200), axis = 0)) # not command ~

[[  1   2   3   4   5   6   7   8   9   0]
 [ 11  22  33  44  55  66  77  88  99   0]
 [111 222 333 444 555 666 777 888 999   0]]
[[False False False False False False False False False False]
 [False  True  True  True  True  True  True  True  True False]
 [ True  True  True  True  True  True  True  True  True False]]
[ 1  2  3  4  5  6  7  8  9  0 11  0  0]
[False False False  True  True  True  True  True  True False]
[ True False False False False False False False False  True]
[False False False False False False False False False False]
